
import ProgressBar from '@/components/layout/loading';
import { myCustomFont } from '@/lib/fonts';
import '../lib/globals.css';
import '../lib/fontawesome'

export const metadata = {
  title: 'TTA Land',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${myCustomFont.className} relative`}>
        <div className='h-full w-full bg-[url(/img/background.jpg)] bg-cover bg-center bg-no-repeat fixed brightness-50'></div>
        <ProgressBar/>
        <div className='absolute w-full top-0'>
          {children}
        </div>
      </body>
    </html>
  )
}
