
import ProgressBar from '@/components/layout/loading';
import { myCustomFont } from '@/lib/fonts';
import '../lib/globals.css';
import '../lib/fontawesome'

export const metadata = {
  title: 'TTA Land',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${myCustomFont.className} bg-white text-black`}>
        <ProgressBar/>
        {children}
      </body>
    </html>
  )
}
