
import '../lib/globals.css';
import '../lib/fontawesome'
import _navbar from '@/components/navbar';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <_navbar/>
        {children}
      </body>
    </html>
  )
}
