import { myCustomFont } from '@/lib/fonts';
import '../lib/globals.css';
import '../lib/fontawesome'
import _navbar from '@/components/layout/navbar';
export const metadata = {
  title: 'TTA Land',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${myCustomFont.className} relative`}>
        <div className='h-full w-full bg-[url(/img/showcase.png)] bg-cover bg-center bg-no-repeat fixed brightness-70'></div>
        <div className='absolute w-full top-0'>
          <_navbar/> 
          {children}
        </div>
      </body>
    </html>
  )
}
